development:
  adapter: postgresql
  encoding: unicode
  database: record_text_dev
  pool: 5
  username: ducle
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: record_text_test
  pool: 5
  username: ducle
  password:
